# Define criteria for various workouts.
CRITERIA = {
    "Squat": [
        {
            "name": "knees",
            "description": "Knees reach 90 degrees",
            "long_description": "The angle between your hip, knee, and ankle must reach 90 degrees. Your thigh should be parallel to the ground.",
            "condition": lambda angles: angles["right_hipright_knee"] <= 90,
            "requirement": "require",
            "feedback_fail": "Lower your squat to at least 90 degrees!",
            "feedback_pass": "Great depth! Keep it up!",
        },
        {
            "name": "shoulders",
            "description": "Shoulders remain level",
            "long_description": "Your shoulders should be at the same height during the squat to avoid tilting.",
            "condition": lambda angles: angles["left_shoulderright_shoulder"] < 10,
            "requirement": "avoid",
            "feedback_fail": "Keep your shoulders level while squatting!",
            "feedback_pass": "Nice! Your shoulders stayed balanced!",
        },
        {
            "name": "torso",
            "description": "Torso remains upright",
            "long_description": "Your back should be straight, and eyes forward.",
            "condition": lambda angles: angles["right_shoulderright_hip"] >= 70,
            "requirement": "avoid",
            "feedback_fail": "Straighten your back and look forward!",
            "feedback_pass": "Great posture!",
        },
    ],
    "Push-Up": [
        {
            "name": "level-shoulders",
            "description": "Shoulders stay level",
            "long_description": "Your shoulders should not tilt past 25 degrees.",
            "condition": lambda angles: angles["left_shoulderright_shoulder"] < 25,
            "requirement": "avoid",
            "feedback_fail": "Keep your shoulders steady during push-ups!",
            "feedback_pass": "Good control over your shoulders!",
        },
        {
            "name": "tricep",
            "description": "Arms fully extend",
            "long_description": "At the top position, your triceps should form a 90-degree angle with the ground.",
            "condition": lambda angles: angles["right_shoulderright_elbow"] >= 80,
            "requirement": "require",
            "feedback_fail": "Extend your arms fully at the top!",
            "feedback_pass": "Good full extension!",
        },
        {
            "name": "body-alignment",
            "description": "Body remains straight",
            "long_description": "Your body should form a straight line from your shoulder to your hip.",
            "condition": lambda angles: angles["body_alignment"] < 10,
            "requirement": "require",
            "feedback_fail": "Keep your core engaged and maintain a straight body!",
            "feedback_pass": "Great body alignment!",
        },
        {
            "name": "elbow-flare",
            "description": "Elbows remain tucked",
            "long_description": "Your elbows should stay close to your midline instead of flaring out.",
            "condition": lambda angles: angles["elbow_offset_ratio"] < 0.3,
            "requirement": "avoid",
            "feedback_fail": "Tuck your elbows in closer to your body!",
            "feedback_pass": "Good elbow position!",
        },
    ],
    "Sit-Up": [
        {
            "name": "up-position",
            "description": "Back gets perpendicular to ground",
            "long_description": "When you are in the 'up' position, your back should be at least 75 degrees.",
            "condition": lambda angles: angles["right_shoulderright_hip"] >= 75,
            "requirement": "require",
            "feedback_fail": "Sit up higher to reach the correct position!",
            "feedback_pass": "Good sit-up position!",
        },
        {
            "name": "down-position",
            "description": "Back gets horizontal to ground",
            "long_description": "When you are in the down position, your back should be flat with the ground, including your neck.",
            "condition": lambda angles: angles["left_shoulderleft_hip"] <= 5,
            "requirement": "require",
            "feedback_fail": "Lie back fully to complete the rep!",
            "feedback_pass": "Nice full range of motion!",
        },
        {
            "name": "bent legs",
            "description": "Legs stay bent",
            "long_description": "During a sit-up, your legs should stay bent and not move excessively.",
            "condition": lambda angles: angles["right_hipright_knee"] <= 10,
            "requirement": "avoid",
            "feedback_fail": "Keep your legs stable and bent throughout the movement!",
            "feedback_pass": "Great job keeping your legs steady!",
        },
    ]
}